# Generated by Django 5.1.2 on 2024-10-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="firstname",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="lastname",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
